import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { GlobalContextProvider } from "@/contexts/WalletContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={"dark:bg-neutral-900"} lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Header></Header>

          {children}
          <Footer></Footer>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
